# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name sample_binom
#' @noRd
sample_binom <- function(y_matrix, Ni, X, beta_old, nsave, nburn, A0, d0, D0, G0, BOOST, verbose, prior_ig) {
    .Call(`_UPG_sample_binom`, y_matrix, Ni, X, beta_old, nsave, nburn, A0, d0, D0, G0, BOOST, verbose, prior_ig)
}

#' @name sample_logit
#' @noRd
sample_logit <- function(y_matrix, y_categ, X, beta_old, nsave, nburn, A0, d0, D0, G0, BOOST, verbose) {
    .Call(`_UPG_sample_logit`, y_matrix, y_categ, X, beta_old, nsave, nburn, A0, d0, D0, G0, BOOST, verbose)
}

#' @name sample_mnl
#' @noRd
sample_mnl <- function(y_matrix, y_categ, X, beta_old, nsave, nburn, A0, d0, D0, G0, BOOST, verbose) {
    .Call(`_UPG_sample_mnl`, y_matrix, y_categ, X, beta_old, nsave, nburn, A0, d0, D0, G0, BOOST, verbose)
}

#' @name sample_probit
#' @noRd
sample_probit <- function(y_matrix, y_categ, X, beta_old, nsave, nburn, A0, d0, D0, G0, BOOST, verbose) {
    .Call(`_UPG_sample_probit`, y_matrix, y_categ, X, beta_old, nsave, nburn, A0, d0, D0, G0, BOOST, verbose)
}

